// Generated by CoffeeScript 1.9.3
(function() {
  var getParameterByName, path;

  getParameterByName = function(name) {
    var i, len, p, param, params;
    params = window.location.search.substr(1).split("&");
    for (i = 0, len = params.length; i < len; i++) {
      param = params[i];
      p = param.split('=');
      if (p[0] === name) {
        return p[1];
      }
    }
    return '';
  };

  window.delayRedirectToModule = function() {
    return setInterval(function() {
      return location.reload();
    }, 3000);
  };

  path = [location.protocol, '//', location.host, location.pathname].join('');

  if (window.location !== path) {
    if (getParameterByName('remove') === '1') {
      window.location.href = path;
    }
    if (getParameterByName('cb_return_status') && getParameterByName('cb_return_status') !== 'success') {
      setTimeout(function() {
        return window.location.href = path;
      }, 3000);
    }
  }

}).call(this);
