<div id="redirect_to", data-url="$this->url" data-path='connections?partner=true'></div>
<div class="chargeback_plugin_header_container">
  <img src="{$this->skin_url}images/chargeback/2016-horizontal-400px.png" class="chargeback_plugin_logo">
  <span class="chargeback_plugin_header"> Automated Chargeback Management &amp; Reporting</span>
</div>
<div>
  <div class="chargeback_plugin_left chargeback_plugin_wbg">
    <img src="{$this->skin_url}images/chargeback/connected.png" class="chargeback_plugin_cbdemo">
    <p>T Your account is currently connected to Chargeback.</p>
    <hr>
    <div style='float: right;'>
      <a href="?remove=1" class="links" style="padding-right: 50px">DISCONNECT</a>
      <a href="{$this->url}connections" target="_blank" class="links">VIEW DASHBOARD</a>
    </div>
  </div>
  <div class="chargeback_plugin_clearfix"></div>
</div>