<?php
  $url              = Mage::getStoreConfig('chargeback/general/url');
  $auth             = $this->getRequest()->getParam('_cb_auth_token');
  $error            = $this->getRequest()->getParam('cb_error_message');
  $status           = $this->getRequest()->getParam('cb_return_status');
  $helper           = Mage::helper('chargeback_auth');
  $complete         = $helper->getComplete();

  $connectUrlString = '';
  if ($auth) {
      if(!$complete && !$status){
        $connectUrlString = $helper->connect();
      }
      if ($status != 'success') {
          $redirect = $connectUrlString;
      }
  }
?>
<div id="chargeback-plugin">
  <?php if(($auth && !$status) || $status == 'success'){ ?>
    <?php $redirect = $status == 'success' ? $url."connections?partner=true" : "$connectUrlString" ?>
    <meta http-equiv='refresh' content="2;url='<?=$redirect?>'">
  <?php } ?>
  <div class="row">
    <p>
      <div class="chargeback_plugin_header_container">
        <img src="<?=$this->getSkinUrl()?>images/chargeback/2016-horizontal-400px.png" class="chargeback_plugin_logo">
        <span class="chargeback_plugin_header">Automated Chargeback Management &amp; Reporting</span>
        <?php if(!$auth && $complete != true){ ?>
          <a class='chargeback_plugin_button' href='<?=$url?>auth_tokens/new?location=login' target="_blank" onclick="delayRedirectToModule();">Connect Chargeback</a>
        <?php } ?>
      </div>
      <div class ="row">
        <div class="chargeback_plugin_left chargeback_plugin_wbg">
          <?php if($complete == true){ ?>
            <img src="<?=$this->getSkinUrl()?>images/chargeback/connected.png" class="chargeback_plugin_cbdemo">
            <p>Your account is currently connected to Chargeback.</p>
            <hr>
            <div style='float: right;'>
              <a href="?remove=1" class="links" style="padding-right: 50px">DISCONNECT</a>
              <a href="<?=$url?>connections" target="_blank" class="links">VIEW DASHBOARD</a>
            </div>
          <?php } elseif($auth && !$status) { ?>
            <img src='<?=$this->getSkinUrl()?>images/chargeback/connecting-magento.gif' class='chargeback_plugin_cbdemo'>
            <h2>Activating API-Key...</h2>
            <p>If you are not redirected in 10 seconds <a href='<?=$connectUrlString?>'>click here</a></p>
          <?php } elseif($auth != FALSE && $status != 'success'){ ?>
            <p>Something went wrong updating your API key. Please try again in a few minutes or contact <a href='https://chargeback.com/contact/' target='_blank'>Chargeback support</a>.</p>
          <?php } else { ?>
            <img src='<?=$this->getSkinUrl()?>images/chargeback/cb-demo.gif' class='chargeback_plugin_cbdemo'>
            <p>Connect your account with Chargeback to link data.</p>
            <hr>
            <div style="text-align: center; padding-top: 10px; padding-right: 10px; float: right;">
            </div>
          <?php } ?>
        </div>
      </div>
    </p>
  </div>
  <?php if(!$complete && (!$auth || $status)){ ?>
    <div class='chargeback_plugin_left'>
      <h2>Why Chargeback?</h2>
      <p>Understand your situation, recover lost revenue, and protect your merchant account now.</p>
      <p><img src='<?=$this->getSkinUrl()?>images/chargeback/0-free.png' class='chargeback_plugin_bicon'>Free To Get Started</p>
      <p><img src='<?=$this->getSkinUrl()?>images/chargeback/0-recovered.png' class='chargeback_plugin_bicon'>Recovered Revenue Billing Model</p>
      <p><img src='<?=$this->getSkinUrl()?>images/chargeback/0-secure.png' class='chargeback_plugin_bicon'>Secure Data Encryption</p>
      <p><img src='<?=$this->getSkinUrl()?>images/chargeback/0-quality.png' class='chargeback_plugin_bicon'>Quality Assurance Reviews</p>
    </div>
    <div class='chargeback_plugin_clearfix'></div>
  <?php } ?>
</div>